version: '3'

services:
  qlx:
    image: qlx:latest
    build:
      context: ./qlx/
    links:
      - "redis-qlx:redis"
    ports:
      - "27960:27960/udp"
      - "27960:27960/tcp"
    restart: always
    environment:
      - "public=0"
      - "gameport=27960"
      - "name=QLChill"
      - "location=Frankfurt"
      - "tags=chill,ft,minqlx"
      - "mappool=qlxft"
      - "rcon_password=hackme"
  redis-qlx:
    image: redis
    restart: always
    volumes:
      - ./data/redis:/data:rw
